title: Tailwind Jekyll Starter Kit
description: A starter kit for using Tailwind with Jekyll

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - package-lock.json
  - Gemfile
  - Gemfile.lock
